# Generated by Django 3.2.21 on 2026-07-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTPSendQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('send_date', models.DateField()),
                ('send_count', models.PositiveIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('cooldown_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-send_date', 'email'],
                'unique_together': {('email', 'send_date')},
            },
        ),
    ]
